### ISSUE TITLE
Link de transição

### ISSUE THREAD

**Issue by iaurg** [IUX7K/ux4noobs#3]
Olá, tudo certo?

Ví que os documentos seguem uma ordem, o que acha de colocarmos um link para o próximo documento no final de cada página? Isso fará com que o usuário possa seguir um fluxo sem ter que ficar indo e voltando para ler.

**Comment by danielhe4rt** [comment]
Olá iaurg!

A ideia é ótima e eu acho que se você tiver o conhecimento necessário seria bem legal você mandar esse pull request pra análise.

**Comment by iaurg** [comment]
Perfeito.

Enviei o PR #4

**Comment by arantesxyz** [comment]
@iaurg Acho que ficaria mais top ainda se fosse adicionado links para voltar para a página anterior.
